version: '3'
services:
  flasky:
    build: .
    env_file: .env
    volumes:
      - ./logs:/home/flasky/logs
    restart: always
    links:
      - mysql:dbserver
    networks:  # <-- here
      - nginx_network
      - database_network

  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:  # <-- connect to the bridge
      - database_network

  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - flasky
    networks:  # <-- here
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  database_network:  # <-- add the bridge
    driver: bridge