"""empty message

Revision ID: 86e9d9cf4a78
Revises: fe8bd556287f
Create Date: 2018-10-17 12:18:09.349736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e9d9cf4a78'
down_revision = 'fe8bd556287f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_evaluate',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('food_id', 'user_id')
    )
    op.create_table('hotel_evaluate',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'user_id')
    )
    op.create_table('traffic_evaluate',
    sa.Column('traffic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['traffic_id'], ['traffic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('traffic_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_evaluate')
    op.drop_table('hotel_evaluate')
    op.drop_table('food_evaluate')
    # ### end Alembic commands ###
