"""empty message

Revision ID: 8bf685a77ff2
Revises: 7c077f281460
Create Date: 2018-10-16 10:43:03.090810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf685a77ff2'
down_revision = '7c077f281460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('support_num', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic', 'support_num')
    # ### end Alembic commands ###
